// This file is automatically generated by the package manager, do not edit it

use anyhow::Result;
use arcstr::ArcStr;
use fxhash::FxHashMap;
use graphix_compiler::{env::Env, ExecCtx};
use graphix_package::{CustomDisplay, IndexSet, Package};
use graphix_rt::{CompExp, GXExt, GXHandle, GXRt};
use netidx_core::path::Path;
use tokio::sync::oneshot;

pub(crate) struct RegisterResult {
    pub root: ArcStr,
    pub main_program: Option<&'static str>,
    pub main_thread: Option<graphix_package::MainThreadFn>,
}

pub(crate) fn register<X: GXExt>(
    ctx: &mut ExecCtx<GXRt<X>, X::UserEvent>,
    modules: &mut FxHashMap<Path, ArcStr>,
) -> Result<RegisterResult> {
    let mut root_mods = IndexSet::new();
    graphix_package_core::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_array::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_str::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_map::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_fs::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_net::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_time::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_re::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_rand::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_tui::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_gui::P::register(ctx, modules, &mut root_mods)?;
    let mut parts = Vec::new();
    for name in &root_mods {
        if name == "core" {
            parts.push(format!("mod core;\nuse core"));
        } else {
            parts.push(format!("mod {name}"));
        }
    }
    let mut main_thread = None;
    macro_rules! collect_main_thread {
        ($pkg:path) => {
            if main_thread.is_none() {
                main_thread = <$pkg as Package<X>>::MAIN_THREAD;
            }
        };
    }
    collect_main_thread!(graphix_package_core::P);
    collect_main_thread!(graphix_package_array::P);
    collect_main_thread!(graphix_package_str::P);
    collect_main_thread!(graphix_package_map::P);
    collect_main_thread!(graphix_package_fs::P);
    collect_main_thread!(graphix_package_net::P);
    collect_main_thread!(graphix_package_time::P);
    collect_main_thread!(graphix_package_re::P);
    collect_main_thread!(graphix_package_rand::P);
    collect_main_thread!(graphix_package_tui::P);
    collect_main_thread!(graphix_package_gui::P);
    Ok(RegisterResult {
        root: ArcStr::from(parts.join(";\n")),
        main_program: None,
        main_thread,
    })
}

pub(crate) struct Cdc<X: GXExt> {
    pub stop: oneshot::Receiver<()>,
    pub custom: Box<dyn CustomDisplay<X>>,
}

pub(crate) enum CustomResult<X: GXExt> {
    Custom(Cdc<X>),
    NotCustom(CompExp<X>),
}

pub(crate) fn maybe_init_custom<X: GXExt>(
    gx: &GXHandle<X>,
    env: &Env,
    e: CompExp<X>,
    main_thread_rx: Option<graphix_package::MainThreadRx>,
) -> Result<CustomResult<X>> {
    macro_rules! try_pkg {
        ($pkg:path) => {
            if <$pkg>::is_custom(gx, env, &e) {
                let (tx, rx) = oneshot::channel();
                return <$pkg>::init_custom(gx, env, tx, e, main_thread_rx)
                    .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
            }
        };
    }
    try_pkg!(graphix_package_core::P);
    try_pkg!(graphix_package_array::P);
    try_pkg!(graphix_package_str::P);
    try_pkg!(graphix_package_map::P);
    try_pkg!(graphix_package_fs::P);
    try_pkg!(graphix_package_net::P);
    try_pkg!(graphix_package_time::P);
    try_pkg!(graphix_package_re::P);
    try_pkg!(graphix_package_rand::P);
    try_pkg!(graphix_package_tui::P);
    try_pkg!(graphix_package_gui::P);
    Ok(CustomResult::NotCustom(e))
}
