// This file is automatically generated by the package manager, do not edit it

use anyhow::Result;
use arcstr::ArcStr;
use fxhash::FxHashMap;
use graphix_compiler::{env::Env, ExecCtx};
use graphix_package::{CustomDisplay, IndexSet, Package};
use graphix_rt::{CompExp, GXExt, GXHandle, GXRt};
use netidx_core::path::Path;
use tokio::sync::oneshot;

pub(crate) struct RegisterResult {
    pub root: ArcStr,
    pub main_program: Option<&'static str>,
}

pub(crate) fn register<X: GXExt>(
    ctx: &mut ExecCtx<GXRt<X>, X::UserEvent>,
    modules: &mut FxHashMap<Path, ArcStr>,
) -> Result<RegisterResult> {
    let mut root_mods = IndexSet::new();
    graphix_package_core::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_array::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_str::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_map::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_fs::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_net::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_time::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_re::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_rand::P::register(ctx, modules, &mut root_mods)?;
    graphix_package_tui::P::register(ctx, modules, &mut root_mods)?;
    let mut parts = Vec::new();
    for name in &root_mods {
        if name == "core" {
            parts.push(format!("mod core;\nuse core"));
        } else {
            parts.push(format!("mod {name}"));
        }
    }
    Ok(RegisterResult {
        root: ArcStr::from(parts.join(";\n")),
        main_program: None,
    })
}

pub(crate) struct Cdc<X: GXExt> {
    pub stop: oneshot::Receiver<()>,
    pub custom: Box<dyn CustomDisplay<X>>,
}

pub(crate) enum CustomResult<X: GXExt> {
    Custom(Cdc<X>),
    NotCustom(CompExp<X>),
}

pub(crate) fn maybe_init_custom<X: GXExt>(
    gx: &GXHandle<X>,
    env: &Env,
    e: CompExp<X>,
) -> Result<CustomResult<X>> {
    if graphix_package_core::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_core::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_array::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_array::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_str::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_str::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_map::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_map::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_fs::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_fs::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_net::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_net::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_time::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_time::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_re::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_re::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_rand::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_rand::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    if graphix_package_tui::P::is_custom(gx, env, &e) {
        let (tx, rx) = oneshot::channel();
        return graphix_package_tui::P::init_custom(gx, env, tx, e)
            .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
    }
    Ok(CustomResult::NotCustom(e))
}
