//! Registration of additional (external) packages. GENERATED by the graphix
//! package manager — do not edit. The stdlib is registered by
//! `graphix_shell::deps`, gated by Cargo features.
#![allow(unused_imports)]

use ahash::AHashMap;
use anyhow::Result;
use arcstr::ArcStr;
use graphix_compiler::{expr::VfsEntry, ExecCtx};
use graphix_package::{IndexSet, Package};
use graphix_rt::{GXExt, GXRt, NoExt};
use graphix_shell::{
    deps::{Cdc, CustomResult},
    CustomDisplayFn,
};
use netidx_core::path::Path;
use tokio::sync::oneshot;

pub fn register<X: GXExt>(
    ctx: &mut ExecCtx<GXRt<X>, X::UserEvent>,
    modules: &mut AHashMap<Path, VfsEntry>,
    root_mods: &mut IndexSet<ArcStr>,
) -> Result<()> {
    {{#each deps}}
    {{this.crate_name}}::P::register(ctx, modules, root_mods)?;
    {{/each}}
    Ok(())
}

pub fn main_program() -> Option<&'static str> {
    {{#if standalone_crate}}
    <{{standalone_crate}}::P as Package<NoExt>>::main_program()
    {{else}}
    None
    {{/if}}
}

pub fn custom_display<X: GXExt>() -> CustomDisplayFn<X> {
    Box::new(|gx, env, e, run_on_main| {
        Box::pin(async move {
            {{#each deps}}
            if {{this.crate_name}}::P::is_custom(gx, env, &e) {
                let (tx, rx) = oneshot::channel();
                return {{this.crate_name}}::P::init_custom(
                    gx,
                    env,
                    tx,
                    e,
                    run_on_main.clone(),
                )
                .await
                .map(|custom| CustomResult::Custom(Cdc { stop: rx, custom }));
            }
            {{/each}}
            Ok(CustomResult::NotCustom(e))
        })
    })
}
