//! Harvest the full graphix-tests fixture corpus as fuzzer seeds.
//!
//! Every `run!` fixture's program is a `const NAME: &str = "..."` in a
//! test source file. We parse those files with `syn` and extract each
//! const's string value (which `LitStr::value()` returns with `\`-newline
//! continuations and escapes resolved) into `$OUT_DIR/harvested_seeds.rs`,
//! a `pub static HARVESTED: &[&str]`. `corpus.rs` includes it and chains
//! it with the hand-written seeds. This multiplies the transplant
//! cross-product from ~33 hand seeds to the whole ~470-fixture corpus.

use std::fs;
use std::path::Path;

fn collect_consts(items: &[syn::Item], out: &mut Vec<String>) {
    for item in items {
        match item {
            syn::Item::Const(c) => {
                if let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(s), .. }) = &*c.expr {
                    out.push(s.value());
                }
            }
            // Recurse into inline `mod foo { ... }` blocks.
            syn::Item::Mod(m) => {
                if let Some((_, items)) = &m.content {
                    collect_consts(items, out);
                }
            }
            _ => {}
        }
    }
}

fn walk_dir(dir: &Path, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk_dir(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            println!("cargo:rerun-if-changed={}", p.display());
            if let Ok(src) = fs::read_to_string(&p) {
                if let Ok(file) = syn::parse_file(&src) {
                    collect_consts(&file.items, out);
                }
            }
        }
    }
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base = Path::new(&manifest).join("../stdlib/graphix-tests/src");
    let mut seeds = Vec::new();
    for sub in ["lib_tests", "lang"] {
        let d = base.join(sub);
        println!("cargo:rerun-if-changed={}", d.display());
        walk_dir(&d, &mut seeds);
    }
    seeds.sort();
    seeds.dedup();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut content = String::from(
        "// Generated by build.rs from the graphix-tests fixture corpus.\n\
         pub static HARVESTED: &[&str] = &[\n",
    );
    for s in &seeds {
        if s.trim().is_empty() {
            continue;
        }
        // `{:?}` emits a correctly-escaped Rust string literal.
        content.push_str(&format!("    {s:?},\n"));
    }
    content.push_str("];\n");
    fs::write(Path::new(&out_dir).join("harvested_seeds.rs"), content).unwrap();
}
