//! Harvest the full graphix-tests fixture corpus as fuzzer seeds.
//!
//! Every `run!` fixture's program is a `const NAME: &str = "..."` in a
//! test source file. We parse those files with `syn` and extract each
//! const's string value (which `LitStr::value()` returns with `\`-newline
//! continuations and escapes resolved) into `$OUT_DIR/harvested_seeds.rs`,
//! a `pub static HARVESTED: &[&str]`. `corpus.rs` includes it and chains
//! it with the hand-written seeds. This multiplies the transplant
//! cross-product from ~33 hand seeds to the whole ~470-fixture corpus.

use std::{fs, path::Path};

fn collect_consts(items: &[syn::Item], out: &mut Vec<String>) {
    for item in items {
        match item {
            syn::Item::Const(c) => {
                if let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(s), .. }) =
                    &*c.expr
                {
                    out.push(s.value());
                }
            }
            // Recurse into inline `mod foo { ... }` blocks.
            syn::Item::Mod(m) => {
                if let Some((_, items)) = &m.content {
                    collect_consts(items, out);
                }
            }
            _ => {}
        }
    }
}

fn walk_dir(dir: &Path, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk_dir(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            println!("cargo:rerun-if-changed={}", p.display());
            if let Ok(src) = fs::read_to_string(&p) {
                if let Ok(file) = syn::parse_file(&src) {
                    collect_consts(&file.items, out);
                }
            }
        }
    }
}

/// Strip the leading `//`-comment header (and blank lines) from a saved
/// finding so only the graphix program remains — EXCEPT a
/// `// schedule-v1:` line, which is oracle DATA (the injection
/// schedule), not commentary: it is re-attached above the program so
/// the embedded regression entry replays the finding's inputs.
/// Stripping it ran every reactive pin with zero injections — a
/// quiesced-at-init program in both modes, a vacuously-green gate
/// (soak jul04 item 10).
fn strip_header(s: &str) -> String {
    let mut schedule: Option<&str> = None;
    let mut lines = s.lines().peekable();
    while let Some(l) = lines.peek() {
        let t = l.trim_start();
        if t.starts_with("// schedule-v1:") {
            schedule = Some(t);
            lines.next();
        } else if t.starts_with("//") || t.is_empty() {
            lines.next();
        } else {
            break;
        }
    }
    let prog = lines.collect::<Vec<_>>().join("\n");
    match schedule {
        Some(h) if !prog.trim().is_empty() => format!("{h}\n{prog}"),
        _ => prog,
    }
}

/// Walk `findings/**/*.gx`, collecting (relative-name, program) pairs.
fn walk_findings(dir: &Path, base: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk_findings(&p, base, out);
        } else if p.extension().is_some_and(|x| x == "gx") {
            println!("cargo:rerun-if-changed={}", p.display());
            if let Ok(src) = fs::read_to_string(&p) {
                let prog = strip_header(&src);
                if !prog.trim().is_empty() {
                    let name = p.strip_prefix(base).unwrap_or(&p).display().to_string();
                    out.push((name, prog));
                }
            }
        }
    }
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base = Path::new(&manifest).join("../stdlib/graphix-tests/src");
    let mut seeds = Vec::new();
    for sub in ["lib_tests", "lang"] {
        let d = base.join(sub);
        println!("cargo:rerun-if-changed={}", d.display());
        walk_dir(&d, &mut seeds);
    }
    // `#[native]` is a TEST-INFRA assertion (zero node-walk residue at a
    // location; a no-op under --no-fusion) — deliberately mode-asymmetric,
    // so a mutant carrying it into a non-fusable position (e.g. a select
    // arm) CompileErrs under jit only and the oracle records a phantom
    // divergence (soak 2026-07-04). Strip it from the seed pool.
    for s in seeds.iter_mut() {
        if s.contains("#[native]") {
            *s = s.replace("#[native]", "");
        }
    }
    seeds.sort();
    seeds.dedup();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut content = String::from(
        "// Generated by build.rs from the graphix-tests fixture corpus.\n\
         pub static HARVESTED: &[&str] = &[\n",
    );
    for s in &seeds {
        if s.trim().is_empty() {
            continue;
        }
        // `{:?}` emits a correctly-escaped Rust string literal.
        content.push_str(&format!("    {s:?},\n"));
    }
    content.push_str("];\n");
    fs::write(Path::new(&out_dir).join("harvested_seeds.rs"), content).unwrap();

    // The regression corpus: every saved finding under `findings/`, run
    // automatically before each fuzz campaign to catch a fixed bug coming
    // back. Grows by adding `.gx` files to `findings/` and rebuilding.
    let findings = Path::new(&manifest).join("findings");
    println!("cargo:rerun-if-changed={}", findings.display());
    let mut corpus = Vec::new();
    walk_findings(&findings, &findings, &mut corpus);
    corpus.sort();
    corpus.dedup();
    let mut rc = String::from(
        "// Generated by build.rs from graphix-fuzz/findings/.\n\
         pub static REGRESSION_CORPUS: &[(&str, &str)] = &[\n",
    );
    for (name, prog) in &corpus {
        rc.push_str(&format!("    ({name:?}, {prog:?}),\n"));
    }
    rc.push_str("];\n");
    fs::write(Path::new(&out_dir).join("regression_corpus.rs"), rc).unwrap();
}
