[package]
name = "tree-sitter-graphix"
version = "0.9.0"
license = "MIT"
authors = ["Eric Stokes <eestokes@pm.me>"]
edition = "2024"
homepage = "https://graphix-lang.github.io/graphix"
repository = "https://github.com/graphix-lang/graphix"
description = "The tree-sitter grammar for Graphix, a dataflow language for UIs and network programming"
documentation = "https://docs.rs/tree-sitter-graphix"
categories = ["parser-implementations", "text-editors"]

[lib]
path = "lib.rs"

[dependencies]
tree-sitter-language = { workspace = true }

[build-dependencies]
cc = { workspace = true }

[dev-dependencies]
tree-sitter = { workspace = true }
