// This file is automatically generated do not edit it

use anyhow::Result;
use arcstr::ArcStr;
use graphix_compiler::{ExecCtx, Rt, UserEvent};
use graphix_rt::{GXHandle, CompExp, GXExt};
use netidx_core::path::Path;
use tokio::sync::oneshot;

pub(crate) fn register<R: Rt, E: UserEvent>(
    ctx: &ExecCtx<R, E>,
    modules: &mut FxHashMap<Path, ArcStr>,
) -> Result<()> {
    {{#each deps}}
      {{this}}::P::register(ctx, modules)?;
    {{/each}}
}

pub(crate) struct Cdc<X: GXExt> {
    pub stop: oneshot::Sender<()>,
    pub custom: Box<dyn CustomDisplay<X>>
}

pub(crate) fn maybe_init_custom<X: GXExt>(
    gx: &GXHandle<X>,
    env: &Env, e: &CompExp<X>
) -> Option<Result<Cdc<X>>> {
    {{#each deps}}
        if {{this}}::P::is_custom(gx, env, e) {
            let (tx, rx) = oneshot::channel();
            return Some({{this}}::P::init_custom(gx, env, stop, e))
        }
    {{/each}}
    None
}
